### ISSUE TITLE
images in clients section don't highlight

### ISSUE THREAD

**Issue by tejasmanohar** [LanceMatch/LanceMatch#25]
on hover, the image logos in the clients section don't light up on hover. they used to, so i'm guessing uncss removed some styles that trigger this? or maybe it was something else you took out?

**Comment by tejasmanohar** [comment]
what are your thoughts on hover effect vs no hover effect from a design standpoint?

**Comment by mazlix** [comment]
#34 fixed by putting `<img src="{% asset_path %}">` instead of `{% image %}` helper.

**Comment by tejasmanohar** [comment]
still an issue for me. check again? you are using {% asset_path %} but still broken
